[tool.black]
target-version = ["py38"]

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
data_file = ".coverages/.coverage"
disable_warnings = ["no-data-collected"]
omit = [
    ".venv/*",
    "venv/*",
]
source = ["."]

[tool.isort]
atomic = true
profile = "black"
combine_as_imports = true
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = "fastapi"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
ignore_missing_imports = true
